### PR TITLE
Add command's; add_role & add_permission

### PR DESCRIPTION
**Pull request by cesargb**
I hope this command was usefull and you can add at project

### CODE REVIEW

**Comment by freekmurze** [comment]
Could you add tests?

**Comment by cesargb** [comment]
Sure!

**Comment by cesargb** [comment]
Thank Sebastian, you are right.

**Comment by freekmurze** [comment]
Could you also update the readme with a little example of how to use these new commands?

**Comment by cesargb** [comment]
Yes, sure. But i must admit that im a newbie with github. I was delete my fork and refork it newly. I try solve in my side the conficts. But i have in local the change, i suppose than need other pull request. Please be patient with me.

**Pull request closed without merging**
