### PR TITLE
[V5] UUID full support, support for custom key names on Role,Permission model

### PR DESCRIPTION
**Pull request by erikn69**
- UUID full support on all methods
- Support for custom key names on Role,Permission model instead of defaut one.(`'id'`)
- Other small fixes

keeps the same operation as always

### CODE REVIEW

**Comment by freekmurze** [comment]
Thanks! This PR seems to do a lot, I see a new migration in there, which makes me think some of the changes are breaking. 

Could you please break this PR up in smaller ones that are easier to review?

**Comment by erikn69** [comment]
Other migration its only for test

**Comment by erikn69** [comment]
Custom new migration is inside `test` path
>  tests/CreatePermissionCustomTables.php

**Comment by erikn69** [comment]
I am trying to push change but how it is closed it is not working

**Pull request closed without merging**
