### PR TITLE
Add check on helper functions

### PR DESCRIPTION
**Pull request by moeen-basra**
Add check on helper functions  if function already exists.

### CODE REVIEW

**Comment by drbyte** [comment]
Can you explain the scenario where these helper methods conflicted? Which specific packages are conflicting?

**Comment by moeen-basra** [comment]
> Can you explain the scenario where these helper methods conflicted? Which specific packages are conflicting?

Hi, it could conflict with every application which provide support for both Laravel and Lumen.
One of them is https://github.com/moeen-basra/photon

**Comment by drbyte** [comment]
> One of them is https://github.com/moeen-basra/photon

Thanks.

> it could conflict with every application which provide support for both Laravel and Lumen.

Yes, of course. It's a much heated debate around Laravel right now.

I'm not convinced that merely checking `function_exists` is the ultimate best way, since you can't count on the pre-existing function doing what your own app/package/etc expects it to do. Namespacing is safer, and preferable. (So is limiting scope to not supporting things that aren't needed; think YAGNI.)

I'd prefer that we namespace this.

**Comment by drbyte** [comment]
While this file will probably be removed in the next version, will merge for now.
Thanks.

**Pull request merged**
