### PR TITLE
[v6] Add BackedEnum support

### PR DESCRIPTION
**Pull request by drbyte**
Fixes #1991

Note: Requires PHP 8.1+

/cc @ceejayoz
/cc @edalzell

### CODE REVIEW

**Comment by drbyte** [comment]
Feedback welcome. I know there are lots of varying ways people like to implement enums. This covers the basics, but if there are some clear use-cases that aren't supported here, this is a good time to make adjustments.

**Comment by boumanb** [comment]
@drbyte to me this looks like a perfect PR example. It's specific and well-documented. 

> Why is the interface needed?

If I may answer; to assure it's a `BackedEnum`. To quote [from the PHP documentation](https://www.php.net/manual/en/class.backedenum.php#backedenum.intro):

> The BackedEnum interface is automatically applied to backed enumerations by the engine. It may not be implemented by user-defined classes. Enumerations may not override its methods, as default implementations are provided by the engine. It is available only for type checks.

The approach of @drbyte follows the example of the comment in the [BackedEnum PHP documentation](https://www.php.net/manual/en/class.backedenum.php#126826). Although the `BackedEnum` interface may not be implemented it CAN BE extended.

**Comment by edalzell** [comment]
> > Why is the interface needed?
> 
> If I may answer; to assure it's a `BackedEnum`. To quote [from the PHP documentation](https://www.php.net/manual/en/class.backedenum.php#backedenum.intro):
> 
> > The BackedEnum interface is automatically applied to backed enumerations by the engine. It may not be implemented by user-defined classes. Enumerations may not override its methods, as default implementations are provided by the engine. It is available only for type checks.
> 
> The approach of @drbyte follows the example of the comment in the [BackedEnum PHP documentation](https://www.php.net/manual/en/class.backedenum.php#126826). Although the `BackedEnum` interface may not be implemented it CAN BE extended.

Sure but you can do this to get a BackedEnum:

CleanShot 2023-04-11 at 11 11 51@2x

...and  that interface is never checked anywhere, only `BackedEnum`. So it seems like it's not used anywhere?

Sorry for my confusion if I'm way off track here, trying to learn!

**Comment by edalzell** [comment]
To be super clear, I'm talking about this:

CleanShot 2023-04-11 at 11 13 41@2x

**Comment by drbyte** [comment]
> I'll update the code in a bit.

Updated. 
Also revised the docs a bit as well.

Question: For those of you who have been using Enums already, how have you handled `can()` and `@can()` situations? And route middleware parameters?

**Comment by edalzell** [comment]
This is very awesome @drbyte and @erikn69, thanks for doing this!

**Comment by drbyte** [comment]
@erikn69 I'd support a PR for that addition.

**Pull request merged**
