### PR TITLE
Autocomplete all Blade directives via Laravel Idea plugin

### PR DESCRIPTION
**Pull request by maartenpaauw**

### CODE REVIEW

**Comment by drbyte** [comment]
Hi @maartenpaauw Thanks for this. 

Will this same proposal work okay if #2168 gets merged? Or will there be complications for implementing this?

**Comment by maartenpaauw** [comment]
Hi @drbyte, if #2168 gets merged I've to change all the `prefix` and `suffix` values so it will use the same code. Can you ping me when it gets merged? Then I'll rebase my branch and fix the code.

**Comment by erikn69** [comment]
is there a better alternative for #2168?

**Comment by maartenpaauw** [comment]
@erikn69 I think your PR is a great feature addition. My PR has nothing to do how to blade directives work. It's just adding auto-completion for PHPStorm via the plugin Laravel Idea.

**Comment by drbyte** [comment]
@maartenpaauw #2168 has been merged.

**Comment by maartenpaauw** [comment]
@drbyte great! I'll rebase my branch later this week.

**Comment by maartenpaauw** [comment]
@drbyte I've rebased the branch and updated the auto complete directives.

**Comment by drbyte** [comment]
Thanks!

**Pull request merged**
