### PR TITLE
It is better to use a static timestamp for migration filename

### PR DESCRIPTION
**Pull request by LKDevelopment**
Fix for
#73

### CODE REVIEW

**Comment by freekmurze** [comment]
I'm kinda liking that the timestamp is dynamic. There is a check around the migration to make sure that it isn't published twice.

**Comment by LKDevelopment** [comment]
@freekmurze This Check doesn't work correctly. 
"Cannot redeclare class CreatePermissionTables"

When i vendor:push every times a new migration will be created.

**Comment by freekmurze** [comment]
Could you trying dumping composer's autoloader immediately after publishing the migration? This will make the class known to the rest of the code preventing the migration from being published twice.

**Comment by LKDevelopment** [comment]
That fix the issue but isn't as clean as possible. It's cleaner to have a static file name (and the possible to check the file exisits in the migrations dir).

**Comment by freekmurze** [comment]
I'm liking the fact that, when using the current solution, the migration does have the right timestamp and that you can see in the migrations of a project when it was added.

**Comment by LKDevelopment** [comment]
Year the fact is nice, but it would be cleaner to put the filename static and add a Comment into the Migration with the current timestamp

**Comment by freekmurze** [comment]
I guess we have different opinions on which solution is better/cleaner 😄

I'm going to leave it like this. If you need this changed, adapt your  installation manager by running the dump of the autoloader. Or you can also fork this package and maintain your own copy.

**Comment by LKDevelopment** [comment]
I think it is a bug.. You should install a package once, and a package publish the migrations and so one, once. But so you can publish it unlimited times (without run composer dump-autoload)

image

**Pull request closed without merging**
