### PR TITLE
Add roleorpermission blade directive

### PR DESCRIPTION
**Pull request by Te7a-Houdini**
this **PR** adds **@roleorpermission** directive . that do the same behavior of **RoleOrPermissionMiddleware**

### CODE REVIEW

**Comment by drbyte** [comment]
Hi @Te7a-Houdini - thanks.

Can you describe a use-case for this?

I very rarely see a case where either/or makes sense for this when an app is structured with partials related to specific permissions.

**Comment by Te7a-Houdini** [comment]
@drbyte  sure . am currently building an app for pharmacy and the admin of websites assigns dynamic roles and permissions . so i wanted this blade directive to show some dashboard based on role or assigned permission tabs like this screenshot

Screenshot from 2020-02-08 22-59-30

**Comment by drbyte** [comment]
I see. 

I find a more efficient way to handle a Super-Admin role is to actually grant it all permissions, and then the app can organically just test for permissions. Less clutter and less cognitive load that way.

https://docs.spatie.be/laravel-permission/v3/basic-usage/super-admin/
https://docs.spatie.be/laravel-permission/v3/best-practices/roles-vs-permissions/

**Comment by Te7a-Houdini** [comment]
@drbyte aha got it . thanks a lot for help . so i think this PR can be closed

**Comment by drbyte** [comment]
Great. If a stronger use-case comes up, we can revisit it. 

Best of success with your app.

**Pull request closed without merging**
