### PR TITLE
Add optional guard in middleware

### PR DESCRIPTION
**Pull request by lloricode**
Signed-off-by: Lloric Mayuga Garcia <lloricode@gmail.com>

### CODE REVIEW

**Comment by lloricode** [comment]
Hi, can you check this out? or should I close this after 7days

**Comment by drbyte** [comment]
Hi,
Can you provide a test which demonstrates the problem this is solving?

**Comment by lloricode** [comment]
@drbyte thanks will back to here sooner

**Comment by lloricode** [comment]
I notice that  `expected` and `actual` is in opposite value

**Comment by lloricode** [comment]
@drbyte can you check this?

**Comment by drbyte** [comment]
Thanks @lloricode 

Do you mind squashing this to a single commit before it gets merged?

**Comment by lloricode** [comment]
move to #1565

**Pull request closed without merging**
