### PR TITLE
Two roles classes and two permission classes for 2 models

### PR DESCRIPTION
**Pull request by springleng**
#995

### CODE REVIEW

**Comment by drbyte** [comment]
Thanks for this.
Are you comfortable adding a corresponding test?

**Comment by drbyte** [comment]
@springleng Am I correctly interpreting that this should probably be done for `Roles` as well?

**Comment by springleng** [comment]
> @springleng Am I correctly interpreting that this should probably be done for `Roles` as well?

My project environment is as follows:

config/permission.php

```php
<?php

return [

    'models' => [

        /*
         * When using the "HasPermissions" trait from this package, we need to know which
         * Eloquent model should be used to retrieve your permissions. Of course, it
         * is often just the "Permission" model but you may use whatever you like.
         *
         * The model you want to use as a Permission model needs to implement the
         * `Spatie\Permission\Contracts\Permission` contract.
         */

        'permission' => Spatie\Permission\Models\Permission::class,

        /*
         * When using the "HasRoles" trait from this package, we need to know which
         * Eloquent model should be used to retrieve your roles. Of course, it
         * is often just the "Role" model but you may use whatever you like.
         *
         * The model you want to use as a Role model needs to implement the
         * `Spatie\Permission\Contracts\Role` contract.
         */

        'role' => Spatie\Permission\Models\Role::class,

    ],

    ......

```

app\Models\System\Permission.php

```php
<?php

namespace App\Models\System;

use Hyn\Tenancy\Traits\UsesSystemConnection;
use Spatie\Permission\Models\Permission as SpatiePermission;
use Illuminate\Database\Eloquent\SoftDeletes;


class Permission extends SpatiePermission
{
    use UsesSystemConnection, SoftDeletes;

    protected $dates = ['deleted_at'];

    protected $fillable = ['name', 'guard_name'];

    protected $guard_name = 'admin';
}
```

app\Models\System\Role.php

```php
<?php

namespace App\Models\System;

use Hyn\Tenancy\Traits\UsesSystemConnection;
use Spatie\Permission\Models\Role as SpatieRole;
use Illuminate\Database\Eloquent\SoftDeletes;
use Kalnoy\Nestedset\NodeTrait;

class Role extends SpatieRole
{
    use UsesSystemConnection, SoftDeletes, NodeTrait;

    protected $dates = ['deleted_at'];

    protected $casts = [
        'is_role' => 'boolean',
    ];

    protected $fillable = ['name', 'is_role', 'parent_id', 'guard_name'];

    protected $guard_name = 'admin';

    public function admins()
    {
        return $this->belongsToMany(Admin::class, 'model_has_roles', 'role_id', 'model_id');
    }
}
```


app\Models\Tenant\Permission.php

```php
<?php

namespace App\Models\Tenant;

use Hyn\Tenancy\Traits\UsesTenantConnection;
use Illuminate\Support\Collection;
use Spatie\Permission\Models\Permission as SpatiePermission;
use Illuminate\Database\Eloquent\SoftDeletes;


class Permission extends SpatiePermission
{
    use UsesTenantConnection, SoftDeletes;

    protected $dates = ['deleted_at'];

    protected $fillable = ['name', 'parent_id', 'alias', 'guard_name'];

    protected $guard_name = 'user';

    protected static function getPermissions(array $params = []): Collection
    {
        $permissions = static::query()->with('roles')->get();

        foreach ($params as $attr => $value) {
            $permissions = $permissions->where($attr, $value);
        }

        return $permissions;
    }
}
```

app\Models\Tenant\Role.php

```php
<?php

namespace App\Models\Tenant;

use Hyn\Tenancy\Traits\UsesTenantConnection;
use Spatie\Permission\Models\Role as SpatieRole;
use Illuminate\Database\Eloquent\SoftDeletes;
use Kalnoy\Nestedset\NodeTrait;


class Role extends SpatieRole
{
    use UsesTenantConnection, SoftDeletes, NodeTrait;

    protected $dates = ['deleted_at'];

    protected $casts = [
        'is_role' => 'boolean',
    ];

    protected $fillable = ['name', 'is_role', 'parent_id', 'guard_name'];

    protected $guard_name = 'user';

}
```

If you do not override the getPermissions method, get permissions is null, Because the system uses UsesSystemConnection to connect database by default config.

**Comment by xlkit456852** [comment]
Is this support version 2.0 ？

**Comment by drbyte** [comment]
> Is this support version 2.0 ？

It was released in 2.38.0

**Comment by xlkit456852** [comment]
Thanks a lot . It gives me hope . I was wondering if there is a complete usage or document that I can learn to use it ? I saw it require Hyn or other packages ,  and I can't understand the relation between these packages .

**Comment by azeos** [comment]
@springleng Thanks for the example. Just one question, do you need to add `getPermissionClass()` to the `Admin` model? Because I only see `getRoleClass()`.

Thanks!

**Comment by azeos** [comment]
I'll leave this here just in case:

It is necessary to add `getPermissionClass()` to the tenant `Role` class. If not, `syncPermissions()` and `givePermissonTo()` will not work.

**Comment by tsangaris** [comment]
Hi @azeos , @springleng . I am trying to implement this with **Laravel 6,** **Multitenancy 5.5**, **spatie/laravel-permission 3.5**. I have some questions:

1. Is the above implementation valid for my setup mentioned above [**Laravel 6,** **Multitenancy 5.5**, **spatie/laravel-permission 3.5**]?
2. Inside Role and Permission models, I see some columns that do not exist in roles and permissions tables (permissions: parent_id, alias | roles: is_role, parent_id). Were these customizations from your end, or were they used in a previous version of spatie/laravel-permission? Do I need to include them now?
3. Do we still need to override methods from HasRoles trait andSpatie\Permission\Models\Role, Spatie\Permission\Models\Permission classes?

I appreciate your work and time to help.

BR

Christos

**Pull request merged**
