### PR TITLE
permission revoke based on ids as well

### PR DESCRIPTION
**Pull request by tariqali021**

### CODE REVIEW

**Comment by parallels999** [comment]
There is no change

**Comment by parallels999** [comment]
Still, is https://github.com/spatie/laravel-permission/pull/2552/commits/09ebf39819d0f1a83dc008a1f318898e8a450a13 a refactor?

**Comment by tariqali021** [comment]
Yes I found some tweaks & fix it.. my docker is crashing & unable to test.. would be great if you review it carefully..

**Comment by parallels999** [comment]
just do `composer test`

**Comment by parallels999** [comment]
Seems that #2548 does the same, test it

**Comment by tariqali021** [comment]
That's something else.. This change belongs to revoking permission given as int (primary key of permission table). Currently, it is only supporting based on name.

**Comment by parallels999** [comment]
> This change belongs to revoking permission given as int (primary key of permission table). Currently, it is only supporting based on name.

That is exactly what #2548 is adding

**Comment by tariqali021** [comment]
Yes it is also doing the same what I'm trying to achieve but to me it seems not optimized way to do that.. correct me if I'm wrong. That code is finding each individual record from db either based on it or string. but the good thing is that it is revoking based on both primary key & name column

**Comment by parallels999** [comment]
> That code is finding each individual record from db either based on int or string

On `removeRole` yes, on `revokePermissionTo` no, permissions are getting from cache, not from DB

**Comment by tariqali021** [comment]
yes but for very rare and edge case if we don't have cache stored at certain point. but still acceptable because of edge case.

**Comment by parallels999** [comment]
The documentation should also be updated, it says that it only accepts string or Permission object

**Comment by tariqali021** [comment]
yes and also `enum`

**Pull request closed without merging**
