### PR TITLE
Add support for hasAnyRole

### PR DESCRIPTION
**Pull request by lowerends**
This PR fixes issue #11.

### CODE REVIEW

**Comment by freekmurze** [comment]
Nice! On first glance this look ok. Are the blade directives coming soon as well? If so, I'll wait on that before tagging a new version.

**Comment by freekmurze** [comment]
Could you also provide an example in the readme?

**Comment by lowerends** [comment]
I was just working on that :)

**Comment by freekmurze** [comment]
:+1:

**Comment by lowerends** [comment]
Moving on to adding the blade directives now.

**Pull request merged**
