### PR TITLE
Optionally display required permissions in exception message

### PR DESCRIPTION
**Pull request by benyanke**
Resolves issue discussed in #593

### CODE REVIEW

**Comment by benyanke** [comment]
@AlexVanderbist

**Comment by drbyte** [comment]
> Thanks for the patience - this is my first non-docs PR iirc.

Woot!  Good on you for stretching yourself!

**Comment by Jigsaw5279** [comment]
Wouldn't it make sense to pass down the array instead of converting it to a string? Or at least store them within the exception, so you can decide what to do with them yourself (instead of having to parse them from the string again..)

**Comment by Jigsaw5279** [comment]
Added PR #629 which does exactly what I described

**Comment by benyanke** [comment]
Ok, I fixed the issues you mentioned, but styleCI still failed. Where can I see what styleCI is not liking? I just see PR info, no errors there.

**Comment by Jigsaw5279** [comment]
You need to have a space between the if keyword and the opening bracket

**Comment by benyanke** [comment]
Figured it out - found the diff option which displays the issue. I think this PR is ready to go @drbyte. 
StyleCI is pretty awesome, I might have to implement that at work for my dev...

**Comment by drbyte** [comment]
Thanks @benyanke !

**Pull request merged**
