### PR TITLE
Negative permissions

### PR DESCRIPTION
**Pull request by V1nc3VD**

### CODE REVIEW

**Comment by V1nc3VD** [comment]
accident

**Comment by erikn69** [comment]
Don't worry

**Comment by erikn69** [comment]
Also run test locally `./vendor/bin/phpunit`

**Comment by erikn69** [comment]
You can squash commits
`git reset --soft HEAD~` uncommit
`git commit --verbose --amend -C HEAD` add changes to the last commit
`git push origin -f` force push with the new commit

**Comment by erikn69** [comment]
Read this, it works almost like you want
https://github.com/spatie/laravel-permission/discussions/1895#discussioncomment-1523163

**Pull request closed without merging**
