### PR TITLE
[Docs] Update link in direct-permissions.md

### PR DESCRIPTION
**Pull request by sevannerse**
Update missing link.

### CODE REVIEW

**Comment by parallels999** [comment]
it works for me

**Comment by drbyte** [comment]
Thanks!

**Comment by parallels999** [comment]
@drbyte seriusly?? this breaks spatie docs, try https://spatie.be/docs/laravel-permission/v6/basic-usage/direct-permissions, and click on the link, now it is missing and redirects to index

**Comment by drbyte** [comment]
Interesting.  
I checked before merging: the docs website was displaying the URL as plain text, not clickable.

**Comment by drbyte** [comment]
Will do some digging.
Will check other links too. We don't do a lot of cross-linking in these docs, so there aren't many links to double-check.

**Comment by parallels999** [comment]
> was displaying the URL as plain text, not clickable

Yes, but the url point to `.md`

**Comment by drbyte** [comment]
Updated

**Pull request merged**
