### PR TITLE
[v7] Update Role contract to match implementation and fix PhpStan errors

### PR DESCRIPTION
**Pull request by SanderMuller**
Allow BackedEnum and set default guardName

Fixes the following PhpStan error:
```
 ------ -------------------------------------------------------------------- 
  Line   app/Console/Commands/EnsureRolesAndPermissionsAreSetCommand.php     
 ------ -------------------------------------------------------------------- 
  29     Method Spatie\Permission\Contracts\Role::hasPermissionTo() invoked  
         with 1 parameter, 2 required.                                       
         ✏️  app/Console/Commands/EnsureRolesAndPermissionsAreSetCommand.php  
  29     Parameter #1 $permission of method                                  
         Spatie\Permission\Contracts\Role::hasPermissionTo() expects         
         Spatie\Permission\Contracts\Permission|string,                      
         App\Enums\Permissions\PermissionEnum::LOGIN_AS_ANY given.           
         ✏️  app/Console/Commands/EnsureRolesAndPermissionsAreSetCommand.php  
 ------ -------------------------------------------------------------------- 
```

caused by this line in my application:
`$role->hasPermissionTo(PermissionEnum::LOGIN_AS_ANY)`

I am passing an enum instance which is allowed according to the docs, and works, but the interface Docblock does not support this. The other error says I am required to pass two parameters, while the second param (`$guardName`) is optional according to the implementations, but not according to the interface

### CODE REVIEW

**Comment by drbyte** [comment]
I agree with your point.
It may be a breaking change for many though. 
So may have to hold off on this for awhile.

**Comment by SanderMuller** [comment]
> I agree with your point. It may be a breaking change for many though. So may have to hold off on this for awhile.

Maybe we can just update the dockblocks as a patch and then the actual types in a major version?

**Comment by drbyte** [comment]
Yes, that'd be fine.

**Comment by drbyte** [comment]
Added `BackedEnum` in https://github.com/spatie/laravel-permission/commit/59b966fbb201c8dfc97dda31547c90a175f75b02

**Pull request closed without merging**
