### PR TITLE
Issue #493 fix

### PR DESCRIPTION
**Pull request by tarampampam**
Apply `try..catch` to the `HasRoles::bootHasRoles` method (with transaction commiting/rollbacking)

### CODE REVIEW

**Comment by tarampampam** [comment]
@freekmurze | @AlexVanderbist - can you check, apply PR and release updated version?

**Comment by AlexVanderbist** [comment]
Hi! Thanks for the PR but I'm not sure this is a fix for the attached issue. If detaching is somehow unsuccessful I wouldn't want to rollback and simply log the error before continuing to delete the model anyways...

**Comment by tarampampam** [comment]
```bash
$ head -n33 ./app/Models/User.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Auth\Authenticatable;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\DB;
use Spatie\Permission\Traits\HasRoles;
use Throwable;
use Illuminate\Support\Facades\Log;
use App\Models\User\Option;

/**
 * Class User
 *
 * @property int         $id
 * @property string|null $name
 * @property string      $login
 * @property string      $password
 * @property string      $remember_token
 * @property Carbon      $deleted_at
 * @property Carbon      $created_at
 * @property Carbon      $updated_at
 */
class User extends AbstractValidatableModel implements AuthenticatableContract, AuthorizableContract
{
    use Authenticatable, Authorizable, SoftDeletes, Notifiable, HasRoles;

$  kot@kotobook  ~/programming/php/sitesoft/processing   dev ●  art migrate:refresh -vvv       

                                                                                                                      
  [Illuminate\Database\QueryException (42P01)]                                                                        
  SQLSTATE[42P01]: Undefined table: 7 ОШИБКА:  отношение "users_has_roles" не существует                              
  LINE 1: delete from "users_has_roles" where "model_id" = $1 and "mod...                                             
                      ^ (SQL: delete from "users_has_roles" where "model_id" = 1 and "model_type" = App\Models\User)  
                                                                                                                      

Exception trace:
 () at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664
 Illuminate\Database\Connection->runQueryCallback() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Database/Connection.php:624
 Illuminate\Database\Connection->run() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Database/Connection.php:490
 Illuminate\Database\Connection->affectingStatement() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Database/Connection.php:435
 Illuminate\Database\Connection->delete() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2227
 Illuminate\Database\Query\Builder->delete() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Concerns/InteractsWithPivotTable.php:366
 Illuminate\Database\Eloquent\Relations\BelongsToMany->detach() at /home/kot/programming/php/sitesoft/processing/vendor/spatie/laravel-permission/src/Traits/HasRoles.php:18
 App\Models\User::Spatie\Permission\Traits\{closure}() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:349
 Illuminate\Events\Dispatcher->Illuminate\Events\{closure}() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:200
 Illuminate\Events\Dispatcher->dispatch() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:160
 Illuminate\Events\Dispatcher->until() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasEvents.php:148
 Illuminate\Database\Eloquent\Model->fireModelEvent() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:762
 Illuminate\Database\Eloquent\Model->delete() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Database/Eloquent/SoftDeletes.php:33
 App\Models\User->forceDelete() at /home/kot/programming/php/sitesoft/processing/database/migrations/2017_06_30_121429_add_user_administrator.php:37
 AddUserAdministrator->down() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:359
 Illuminate\Database\Migrations\Migrator->Illuminate\Database\Migrations\{closure}() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php:29
 Illuminate\Database\Connection->transaction() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:364
 Illuminate\Database\Migrations\Migrator->runMigration() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:334
 Illuminate\Database\Migrations\Migrator->runDown() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:257
 Illuminate\Database\Migrations\Migrator->rollbackMigrations() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:307
 Illuminate\Database\Migrations\Migrator->resetMigrations() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:285
 Illuminate\Database\Migrations\Migrator->reset() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/ResetCommand.php:68
 Illuminate\Database\Console\Migrations\ResetCommand->handle() at n/a:n/a
 call_user_func_array() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29
 Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:87
 Illuminate\Container\BoundMethod::callBoundMethod() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:31
 Illuminate\Container\BoundMethod::call() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Container/Container.php:549
 Illuminate\Container\Container->call() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Console/Command.php:180
 Illuminate\Console\Command->execute() at /home/kot/programming/php/sitesoft/processing/vendor/symfony/console/Command/Command.php:262
 Symfony\Component\Console\Command\Command->run() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Console/Command.php:167
 Illuminate\Console\Command->run() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Console/Command.php:195
 Illuminate\Console\Command->call() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/RefreshCommand.php:104
 Illuminate\Database\Console\Migrations\RefreshCommand->runReset() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/RefreshCommand.php:55
 Illuminate\Database\Console\Migrations\RefreshCommand->handle() at n/a:n/a
 call_user_func_array() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29
 Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:87
 Illuminate\Container\BoundMethod::callBoundMethod() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:31
 Illuminate\Container\BoundMethod::call() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Container/Container.php:549
 Illuminate\Container\Container->call() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Console/Command.php:180
 Illuminate\Console\Command->execute() at /home/kot/programming/php/sitesoft/processing/vendor/symfony/console/Command/Command.php:262
 Symfony\Component\Console\Command\Command->run() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Console/Command.php:167
 Illuminate\Console\Command->run() at /home/kot/programming/php/sitesoft/processing/vendor/symfony/console/Application.php:888
 Symfony\Component\Console\Application->doRunCommand() at /home/kot/programming/php/sitesoft/processing/vendor/symfony/console/Application.php:224
 Symfony\Component\Console\Application->doRun() at /home/kot/programming/php/sitesoft/processing/vendor/symfony/console/Application.php:125
 Symfony\Component\Console\Application->run() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Console/Application.php:88
 Illuminate\Console\Application->run() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:121
 Illuminate\Foundation\Console\Kernel->handle() at /home/kot/programming/php/sitesoft/processing/artisan:39

                                                                                          
  [Doctrine\DBAL\Driver\PDOException (42P01)]                                             
  SQLSTATE[42P01]: Undefined table: 7 ОШИБКА:  отношение "users_has_roles" не существует  
  LINE 1: delete from "users_has_roles" where "model_id" = $1 and "mod...                 
                      ^                                                                   
                                                                                          

Exception trace:
 () at /home/kot/programming/php/sitesoft/processing/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:107
 Doctrine\DBAL\Driver\PDOStatement->execute() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Database/Connection.php:483
 Illuminate\Database\Connection->Illuminate\Database\{closure}() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Database/Connection.php:657
 Illuminate\Database\Connection->runQueryCallback() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Database/Connection.php:624
 Illuminate\Database\Connection->run() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Database/Connection.php:490
 Illuminate\Database\Connection->affectingStatement() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Database/Connection.php:435
 Illuminate\Database\Connection->delete() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2227
 Illuminate\Database\Query\Builder->delete() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Concerns/InteractsWithPivotTable.php:366
 Illuminate\Database\Eloquent\Relations\BelongsToMany->detach() at /home/kot/programming/php/sitesoft/processing/vendor/spatie/laravel-permission/src/Traits/HasRoles.php:18
 App\Models\User::Spatie\Permission\Traits\{closure}() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:349
 Illuminate\Events\Dispatcher->Illuminate\Events\{closure}() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:200
 Illuminate\Events\Dispatcher->dispatch() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:160
 Illuminate\Events\Dispatcher->until() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasEvents.php:148
 Illuminate\Database\Eloquent\Model->fireModelEvent() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:762
 Illuminate\Database\Eloquent\Model->delete() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Database/Eloquent/SoftDeletes.php:33
 App\Models\User->forceDelete() at /home/kot/programming/php/sitesoft/processing/database/migrations/2017_06_30_121429_add_user_administrator.php:37
 AddUserAdministrator->down() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:359
 Illuminate\Database\Migrations\Migrator->Illuminate\Database\Migrations\{closure}() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php:29
 Illuminate\Database\Connection->transaction() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:364
 Illuminate\Database\Migrations\Migrator->runMigration() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:334
 Illuminate\Database\Migrations\Migrator->runDown() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:257
 Illuminate\Database\Migrations\Migrator->rollbackMigrations() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:307
 Illuminate\Database\Migrations\Migrator->resetMigrations() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:285
 Illuminate\Database\Migrations\Migrator->reset() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/ResetCommand.php:68
 Illuminate\Database\Console\Migrations\ResetCommand->handle() at n/a:n/a
 call_user_func_array() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29
 Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:87
 Illuminate\Container\BoundMethod::callBoundMethod() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:31
 Illuminate\Container\BoundMethod::call() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Container/Container.php:549
 Illuminate\Container\Container->call() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Console/Command.php:180
 Illuminate\Console\Command->execute() at /home/kot/programming/php/sitesoft/processing/vendor/symfony/console/Command/Command.php:262
 Symfony\Component\Console\Command\Command->run() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Console/Command.php:167
 Illuminate\Console\Command->run() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Console/Command.php:195
 Illuminate\Console\Command->call() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/RefreshCommand.php:104
 Illuminate\Database\Console\Migrations\RefreshCommand->runReset() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/RefreshCommand.php:55
 Illuminate\Database\Console\Migrations\RefreshCommand->handle() at n/a:n/a
 call_user_func_array() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29
 Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:87
 Illuminate\Container\BoundMethod::callBoundMethod() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:31
 Illuminate\Container\BoundMethod::call() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Container/Container.php:549
 Illuminate\Container\Container->call() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Console/Command.php:180
 Illuminate\Console\Command->execute() at /home/kot/programming/php/sitesoft/processing/vendor/symfony/console/Command/Command.php:262
 Symfony\Component\Console\Command\Command->run() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Console/Command.php:167
 Illuminate\Console\Command->run() at /home/kot/programming/php/sitesoft/processing/vendor/symfony/console/Application.php:888
 Symfony\Component\Console\Application->doRunCommand() at /home/kot/programming/php/sitesoft/processing/vendor/symfony/console/Application.php:224
 Symfony\Component\Console\Application->doRun() at /home/kot/programming/php/sitesoft/processing/vendor/symfony/console/Application.php:125
 Symfony\Component\Console\Application->run() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Console/Application.php:88
 Illuminate\Console\Application->run() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:121
 Illuminate\Foundation\Console\Kernel->handle() at /home/kot/programming/php/sitesoft/processing/artisan:39

                                                                                          
  [PDOException (42P01)]                                                                  
  SQLSTATE[42P01]: Undefined table: 7 ОШИБКА:  отношение "users_has_roles" не существует  
  LINE 1: delete from "users_has_roles" where "model_id" = $1 and "mod...                 
                      ^                                                                   
                                                                                          

Exception trace:
 () at /home/kot/programming/php/sitesoft/processing/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105
 PDOStatement->execute() at /home/kot/programming/php/sitesoft/processing/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105
 Doctrine\DBAL\Driver\PDOStatement->execute() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Database/Connection.php:483
 Illuminate\Database\Connection->Illuminate\Database\{closure}() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Database/Connection.php:657
 Illuminate\Database\Connection->runQueryCallback() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Database/Connection.php:624
 Illuminate\Database\Connection->run() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Database/Connection.php:490
 Illuminate\Database\Connection->affectingStatement() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Database/Connection.php:435
 Illuminate\Database\Connection->delete() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2227
 Illuminate\Database\Query\Builder->delete() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Concerns/InteractsWithPivotTable.php:366
 Illuminate\Database\Eloquent\Relations\BelongsToMany->detach() at /home/kot/programming/php/sitesoft/processing/vendor/spatie/laravel-permission/src/Traits/HasRoles.php:18
 App\Models\User::Spatie\Permission\Traits\{closure}() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:349
 Illuminate\Events\Dispatcher->Illuminate\Events\{closure}() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:200
 Illuminate\Events\Dispatcher->dispatch() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:160
 Illuminate\Events\Dispatcher->until() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasEvents.php:148
 Illuminate\Database\Eloquent\Model->fireModelEvent() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:762
 Illuminate\Database\Eloquent\Model->delete() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Database/Eloquent/SoftDeletes.php:33
 App\Models\User->forceDelete() at /home/kot/programming/php/sitesoft/processing/database/migrations/2017_06_30_121429_add_user_administrator.php:37
 AddUserAdministrator->down() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:359
 Illuminate\Database\Migrations\Migrator->Illuminate\Database\Migrations\{closure}() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php:29
 Illuminate\Database\Connection->transaction() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:364
 Illuminate\Database\Migrations\Migrator->runMigration() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:334
 Illuminate\Database\Migrations\Migrator->runDown() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:257
 Illuminate\Database\Migrations\Migrator->rollbackMigrations() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:307
 Illuminate\Database\Migrations\Migrator->resetMigrations() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:285
 Illuminate\Database\Migrations\Migrator->reset() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/ResetCommand.php:68
 Illuminate\Database\Console\Migrations\ResetCommand->handle() at n/a:n/a
 call_user_func_array() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29
 Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:87
 Illuminate\Container\BoundMethod::callBoundMethod() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:31
 Illuminate\Container\BoundMethod::call() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Container/Container.php:549
 Illuminate\Container\Container->call() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Console/Command.php:180
 Illuminate\Console\Command->execute() at /home/kot/programming/php/sitesoft/processing/vendor/symfony/console/Command/Command.php:262
 Symfony\Component\Console\Command\Command->run() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Console/Command.php:167
 Illuminate\Console\Command->run() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Console/Command.php:195
 Illuminate\Console\Command->call() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/RefreshCommand.php:104
 Illuminate\Database\Console\Migrations\RefreshCommand->runReset() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/RefreshCommand.php:55
 Illuminate\Database\Console\Migrations\RefreshCommand->handle() at n/a:n/a
 call_user_func_array() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29
 Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:87
 Illuminate\Container\BoundMethod::callBoundMethod() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:31
 Illuminate\Container\BoundMethod::call() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Container/Container.php:549
 Illuminate\Container\Container->call() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Console/Command.php:180
 Illuminate\Console\Command->execute() at /home/kot/programming/php/sitesoft/processing/vendor/symfony/console/Command/Command.php:262
 Symfony\Component\Console\Command\Command->run() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Console/Command.php:167
 Illuminate\Console\Command->run() at /home/kot/programming/php/sitesoft/processing/vendor/symfony/console/Application.php:888
 Symfony\Component\Console\Application->doRunCommand() at /home/kot/programming/php/sitesoft/processing/vendor/symfony/console/Application.php:224
 Symfony\Component\Console\Application->doRun() at /home/kot/programming/php/sitesoft/processing/vendor/symfony/console/Application.php:125
 Symfony\Component\Console\Application->run() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Console/Application.php:88
 Illuminate\Console\Application->run() at /home/kot/programming/php/sitesoft/processing/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:121
 Illuminate\Foundation\Console\Kernel->handle() at /home/kot/programming/php/sitesoft/processing/artisan:39
```

**Comment by tarampampam** [comment]
Oh, sorry, not here

**Pull request closed without merging**
