### PR TITLE
update arguments Docblock to string|Permission

### PR DESCRIPTION
**Pull request by adaojunior**

### CODE REVIEW

**Comment by adaojunior** [comment]
I just noticed that `hasDirectPermission` is type hinting `$permission` as `Permission`, but it stills checks if `$permission` is string.
Should we change it to `hasDirectPermission($permission)`, otherwise it is gonna faild when trying to pass a string.

**Comment by freekmurze** [comment]
Nice catch. Thank you very much for correcting it.

**Comment by adaojunior** [comment]
@freekmurze what about `hasDirectPermission` expecting a `Permission` ?

**Comment by adaojunior** [comment]
https://github.com/spatie/laravel-permission/pull/51

**Pull request merged**
