### PR TITLE
Add unique columns

### PR DESCRIPTION
**Pull request by lloricode**
This will make sure a unique values in two columns, a name and guard_name

### CODE REVIEW

**Comment by drbyte** [comment]
Please explain "why".

The package already enforces unique combinations, via code.

**Comment by lloricode** [comment]
HI @drbyte,

Yes it already has, I made this PR to also optimize migration according to code implementation.

**Comment by drbyte** [comment]
I'm not convinced this is necessary. Particularly when there are future plans to drop guard-specific db storage.

How in your application is there a need for this?

**Comment by lloricode** [comment]
> Particularly when there are future plans to drop guard-specific db storage.

@drbyte you right thanks :+1:

**Comment by ZaidBarghouthi** [comment]
@drbyte 
> ... future plans to drop guard-specific db storage.

Can you elaborate on this please.

**Comment by drbyte** [comment]
> ... future plans to drop guard-specific db storage.

@ZaidBarghouthi I mean the majority of apps I've seen people using this for are assigning the *same* permissions to both `web` and `api` guards (and any other guards), meaning there's functionally *no* need to define a specific role+guard or permission+guard relation.  So, dropping the `guard_name` field from both tables is what `v3` will be doing. 
There are some other Issues where this has been discussed in more detail.

**Pull request closed without merging**
