### PR TITLE
Unified morph table for permissions

### PR DESCRIPTION
**Pull request by sergiz**
This is a follow-up from #1102.

I made it completely optional. This change does not make any difference for existing (or future) users, if they do not opt-in for it.

It  basically checks, if the config value 'permission.table_names.role_has_permissions' exists and, if it does there is no difference from now. If this value is not set, then the role_has_permissions table will not be created (and used) and model_has_permissions will be used instead (like for any other model).

It gives the end user completely free hands to decide whether they want completely separate table to handle role's permissions, or to use the existing model's table.

### CODE REVIEW

**Comment by drbyte** [comment]
@sergiz Thanks for this.
I keep meaning to sit and inspect whether any additional tests should be included for this change, but haven't had the time to think it through. 
Your thoughts?

**Comment by sergiz** [comment]
Yeah, I could make create some tests. Hopefully I find time to do that soon.

**Comment by drbyte** [comment]
Given MorphToMany inherits from BelongsToMany, can we just leave the BelongsToMany as the return type?

**Comment by sergiz** [comment]
Sorry that it's taking so long, but I'm fully occupied until October. I will look into all these issues then.

**Comment by sergiz** [comment]
Okay, I addressed your concerns now.

a) BelongsToMany return type declaration cannot be left there, as PHP requires it to exactly match the returned instance, so MorpthToMany will not satisfy it. This is one of the reasons why I even made this PR, as I couldn't make this change on my local copy without maintaing my own fork of this package.

b) I added a few tests to make sure that everything is working.

**Comment by drbyte** [comment]
@sergiz What are your thoughts on switching this to be the default, and the split tables be the optional mode?

**Comment by sergiz** [comment]
I think it would make sense since there is no real benefit of having two tables that do the same thing. However, I would consider this a breaking change that requres a new major version.

If you are going to release a new major version with this, then I would also think about simply removing this option all together and simply make it that unified table is the only option.

**Comment by drbyte** [comment]
> I think it would make sense. However, I would consider this a breaking change that requres a new major version.

Yes, that is what I'm aiming for.

> If you are going to release a new major version with this, then I would also think about simply removing this option all together and simply make it that unified table is the only option.

Thoughts on best practices for people migrating their data from the old table into the new?

**Comment by sergiz** [comment]
There could be a section in the upgrade guide, how to make a migration. Eventually you would have to select relations from role_has_permissions and insert them to model_has_permissions. "models.role" config should be taken into consideration, including possible custom morph map.

This can be achieved on the DB level using a "INSERT INTO SELECT" query.

**Comment by sergiz** [comment]
I think this PR should be reopened since the final decision hasn't been made yet.

**Comment by freekmurze** [comment]
I've decided to not merge this in, to keep that package as small as it can be.

**Comment by sergiz** [comment]
> 
> 
> I've decided to not merge this in, to keep that package as small as it can be.

So 5 tables is less than 4? Interesting.

**Pull request closed without merging**
