### PR TITLE
Remove redundant code in getMigrationFileName() function

### PR DESCRIPTION
**Pull request by jochensengier**
Unless I'm mistaken, these lines can be safely deleted.

### CODE REVIEW

**Comment by drbyte** [comment]
It's true that those lines are not presently needed. 
They were added in order to support the addition of more migration files. Later the decision was to stick with one migration file.

**Comment by drbyte** [comment]
I think there was some intention of using some of that logic to test whether a migration of the same name (but different date) already exists.

**Comment by jochensengier** [comment]
No worries, it's not a big deal, I just wanted to point it out.
Feel free to close my PR.

**Comment by dbakan** [comment]
I think, this should be reopened and merged. The current code does not work as promised and this PR fixes it.

Looks like the problem was introduced with [https://github.com/spatie/laravel-permission/commit/66f6e4a376fed2a3be11605daa4bd02c001c504e](https://github.com/spatie/laravel-permission/commit/66f6e4a376fed2a3be11605daa4bd02c001c504e). As @drbyte said, some lines where added to support multiple migrations, which is great. But it seems that the old lines were left in place unintentionally when they should have been removed.
The hard coded `_create_permission_tables.php` is still in there.

**Comment by drbyte** [comment]
> The current code does not work as promised 

Please elaborate

**Pull request merged**
