### PR TITLE
Add accompanying blade directives

### PR DESCRIPTION
**Pull request by lowerends**
This PR fixes issue #12 as well as #11.

### CODE REVIEW

**Comment by freekmurze** [comment]
Thank you very much! Will review it thoroughly, change some small nitpicks and tag it as a new version.

**Comment by lowerends** [comment]
With pleasure! Just ping me if needed.

**Comment by freekmurze** [comment]
The blade directives do not seem to be working. Have you tested them in a project of your own?

**Comment by lowerends** [comment]
I tested them locally and they seemed to work fine. I did notice that I forgot the `use` statement for `Illuminate\View\Compilers\BladeCompiler` while copying into the PR, but I've seen you noticed that already as well. Sorry for that.

I noticed that you've added tests as well and made some modifications to the directives. Is it working out for you? Definitely let me know if I can be of any assistence.

**Comment by freekmurze** [comment]
I made some modifications so the directives won't break when nobody is logged in. All tests are working now!

I've tagged a new versions. All the new features are present in v1.1.0.

Thanks again! :+1:

**Pull request merged**
