### PR TITLE
Move Permissions Registration to booted method

### PR DESCRIPTION
**Pull request by nisbeti**
When using in memory sqlite database for testing the migrations may not be run until after the boot method, so the ```$permissionLoader->registerPermissions();``` call will fail if called from ```boot()```

https://github.com/spatie/laravel-permission/issues/132 and https://github.com/spatie/laravel-permission/issues/109

This is problematic when when using https://gist.github.com/adamwathan/dd46a8501097942a771925c02bac0111

### CODE REVIEW

**Comment by freekmurze** [comment]
There current tests use an in memory db. They appear to be run fine.

**Comment by bryannielsen** [comment]
@freekmurze The reason it's working fine in the package tests is because the permissions are explicitly reloaded in the `TestCase@setUp()` after the database migrations run (https://github.com/spatie/laravel-permission/blob/master/tests/TestCase.php#L35).

I think there should either be a note for developers to add a similar refresh in their tests (I did this) or change the registration like this PR suggests.

**Comment by freekmurze** [comment]
Can you check if the current `dev-master` fixes this problem?

**Comment by colynb** [comment]
I don't see any documentation that says to use the booted method... I don't see that in Laravel's lifecycle explanation. When is that method called? When I just add that method in one of the providers, there's no indication that it's being called.

**Comment by scottgrayson** [comment]
@bryannielsen could you give an example of how you added a `refresh` in tests

**Comment by nisbeti** [comment]
@colynb booted is used and documented in Laravel Spark which itself is a laravel package.

**Comment by bryannielsen** [comment]
@scottgrayson you can look at the refresh example here - https://github.com/spatie/laravel-permission/blob/master/tests/TestCase.php#L35

Looking at this closer I think doing the refresh in your tests is the only way to do it, the application is fully booted by the time the DatabaseMigrations trait is called and it doesn't look like that trait fires any events to hook into.  Maybe we can just add a note to the readme for this.

**Pull request merged**
