### PR TITLE
feat: check permission based on logged in user guard

### PR DESCRIPTION
**Pull request by Daniyal-Javani**
@musapinar idea to fix https://github.com/spatie/laravel-permission/issues/1313

### CODE REVIEW

**Comment by drbyte** [comment]
@Daniyal-Javani @musapinar 
Do you see any value in some reverse tests? 
Thoughts on whether any other cases need consideration?

**Comment by Daniyal-Javani** [comment]
@drbyte Should I update the document like this?
```
diff --git a/docs/basic-usage/multiple-guards.md b/docs/basic-usage/multiple-guards.md
index 69db924..b244499 100644
--- a/docs/basic-usage/multiple-guards.md
+++ b/docs/basic-usage/multiple-guards.md
@@ -28,7 +28,7 @@ To check if a user has permission for a specific guard:
 
-> **Note**: When determining whether a role/permission is valid on a given model, it chooses the guard in this order: first the `$guard_name` property of the model; then the guard in the config (through a provider); then the first-defined guard in the `auth.guards` config array; then the `auth.defaults.guard` config.
+> **Note**: When determining whether a role/permission is valid on a given model, it chooses the guard in this order: first the guard of logged in user; then the `$guard_name` property of the model; then the guard in the config (through a provider); then the first-defined guard in the `auth.guards` config array; then the `auth.defaults.guard` config.
```

**Comment by drbyte** [comment]
I'm not sure the update to the docs is correct.

I think the correct new explanation is more along the lines of the following (which also feels too verbose for the docs):
- build a list of guards to match against, in this order:
- $guard_name property of the model, if any
- guard names from configured auth providers matching the model, if any
And then find the first one that matches the user's logged-in guard, if any
If not matched, return the actual guard (which the "default" has been updated to, if the user is logged in).

Keep in mind that sometimes there won't be an actual match for the logged-in user: 
- perhaps because the a permissions-check test is triggered before login, 
- it's a create-perm/role call on another model. 

It's this last case (create) that worries me. What about an Administrator, where your app has used an Admin login guard, and you're creating permissions without specifying a guard, and now it's going to default to the admin guard instead of the web guard which non-admins use?

**Comment by thoresuenert** [comment]
I think this solution is way too deep into the logic.

This can (maybe) conflict with admin panels where I want to create auth user independent roles and permission.

I would prefer to pass the auth user guard name during the gate check to `checkPermissionTo` and make it configurable to avoid breaking changes.

**Comment by drbyte** [comment]
> I would prefer to pass the auth user guard name during the gate check to `checkPermissionTo` 

I'd be interested in seeing an implementation of that where the current tests pass. I recall exploring that sort of approach but finding several tests failing (where refactoring those tests wasn't relevant to the code change).

**Pull request closed without merging**
